### ISSUE TITLE
Parsing string concatenation in a MID$ statement

### ISSUE THREAD

**Issue by jggames** [gregdionne/mcbasic#3]
Greg,

This statement didn't seem to work/be parsed by mcbasic.  Compiled without error, but just didn't seem to recognize that there was a string concatentation going on with the string argument of the MID$ command.
S$=S$+MID$(CHR$(95)+LEFT$(A$,16),RND(Y),1)
The result was a string with only the CHRS$(95)s in it.  Just worked around by putting the concatenation outside the MID$ command.  Just thought I should let you know.

Jim

**Comment by gregdionne** [comment]
Thanks for the feedback Jim!

I'll take a look at this later this weekend (hoping to implement LOG, EXP, and SQR then) and see if there's anything obvious.  If not, I'll try to get your particular example that can reproduce the problem reliably... hopefully without relying on RND(). :)  

Best,
-Greg

**Comment by gregdionne** [comment]
All good now.  Thanks for narrowing it down!

-Greg
