### ISSUE TITLE
Your new version killed Qbert!

### ISSUE THREAD

**Issue by jggames** [gregdionne/mcbasic#5]
Greg, just downloaded your latest version of MCBASIC (the one responding to the comment on Facebook about a missing # in some line of your source.  Compiled my latest version of QBERTcompiler21.TXT, and it throws an error after the main game sceen comes up.  Qbert just chucks himself off the top of the pyramid as soon as the screen comes up and then an FC error message is printed .  But the game was compiling fine and behaving as expected when I was compiling under the previous version of MCBasic.

**Comment by jggames** [comment]
Here's a link to my QBert directory.  There's two subdirectories with the "Good" and "Bad" compiles.
[https://github.com/jggames/trs80mc10/tree/master/quicktype/Arcade/QBert](https://github.com/jggames/trs80mc10/tree/master/quicktype/Arcade/QBert)

**Comment by gregdionne** [comment]
Poor Q*bert!

He fell into a regression!  I neglected to save/restore a register when fixing issue #3.   I suppose I am now the target of his famed "language of disaffection."  I'll do a fix on my lunch break.

**Comment by gregdionne** [comment]
Q*bert should be back to his old irascible self now.

**Comment by jggames** [comment]
Dear Greg,

Thanks.  I’ll give it a try soon.  Thanks for your dedication to the project. 

Jim

Sent from Mail for Windows 10
