### ISSUE TITLE
Obscure issue

### ISSUE THREAD

**Issue by jggames** [gregdionne/mcbasic#7]
Hey Greg,
Tried to compile my latest CLOSEOUT.  MCBASIC worked, but TASM reported 
CLOSEOUTcompiler7.asm:5356:9: error: assembly instruction expected
         !unimplemented ireg ireg fext
         ^
(https://github.com/gregdionne/mcbasic/files/6240197/CLOSEOUTcompiler7.TXT)

Just wonderin if you might be able to throw any light.

**Comment by gregdionne** [comment]
Hi Jim,

As always, thanks for the reproduction steps - the bug is fairly simple and related to the "1 AND I" sub-expression in your code at line 63.  I neglected to cast the "I" variable to an integer before invoking the AND instruction.  If you replace that with "1 AND INT(I)" you should be all set until you encounter the next bug.  ;)  

I'll fix it this weekend when I have some time.

**Comment by jggames** [comment]
Dear Greg,

Hope you don’t mind these “issue” reports.  But it makes me feel like “I’m helping,”  Let me know if I become an annoyance.
Hope to have a compiled version out soon.  This game really needs a pick-me-up that I think compiling can provide.  My son Charlie is keen (as much as a 21 year old can be keen) to try a compiled version.   Thanks.

Jim

Sent from Mail for Windows 10

**Comment by gregdionne** [comment]
Hi Jim,

I'm tickled pink that you're generating issue reports.  Keep 'm coming!  One of the challenges of this project is that I don't have a fully-automated test suite - so I resort to running the relevant manual tests in the JavaScript emulator. Those only catch simple cases, and don't catch actual "real world" usage; so I'm very appreciative of posting the problems you find!  Posting here alerts other users of potential issues as well.  

I'm glad Charlie appreciates your creativity!

**Comment by gregdionne** [comment]
Fixed.  ...until you find the next bug.  :)

**Comment by jggames** [comment]
Dear Greg,

Thanks so much. Will download the new version.

Jim

Sent from Mail for Windows 10

**Comment by jggames** [comment]
Dear Greg,

I was doing some recompiling of the prior games I had done using the compiler, just to bring them up to the latest “version.”  I noticed that with my QBERT I get an 
?FS ERROR message while playing the game.  When I play the old compiled version that I have online (compiled with a version a couple of bug fixes back) it works fine.  Now, I could have introduced something in my source code since then that is producing the error, or made some mistake in preserving my source, such that I somehow have a buggy version as my “last” updated version or some such nonsense on my part, but just in case it is some problem introduced in subsequent fixes I thought I should let you know.
Source and ASM attached.

Jim

 

Sent from Mail for Windows 10
